### PR TITLE
Use type-safe access for TypeScript API

### PR DESCRIPTION
**Pull request by seanf**
I also disabled "implicit any", and replaced `isEmptyObject()` with an implementation which should be more efficient. Also tweaked the tests slightly.

### CODE REVIEW

**Comment by seanf** [comment]
Just to clarify:

[byots](https://github.com/basarat/byots) is an unofficial effort to expose the whole compiler API, including internals. It's only needed for one method (`SourceFile.getNamedDeclarations()`). I figure that's okay, because typescript-react-intl already depends on that internal method, just in a non-typesafe way.

The newer version of TypeScript was needed for a missing runtime type-check method (`isStringLiteral()`). I only upgraded to 2.4.x, but perhaps it would be better to upgrade to the latest TypeScript. What would you prefer?

**Comment by BANG88** [comment]
to upgrade to the latest TypeScript version. by the way never used bytos before.

**Comment by BANG88** [comment]
@seanf I think introduce https://github.com/basarat/byots is not a good idea. since this package is simple as it is. so if we can we should use typescript api as we can. what do you think ?

**Comment by seanf** [comment]
@bang88 The code is fairly simple once you understand it, but I found it very difficult to understand the existing code when there were no types for the compiler APIs, especially as I couldn't find much in the way of documentation for those APIs.

But if you prefer, I could remove the byots dependency and use this trick (on line 72):

    var nd = (node as any).getNamedDeclarations();

Would you prefer that?

**Comment by seanf** [comment]
More info about byots here too: https://basarat.gitbooks.io/typescript/docs/compiler/overview.html

**Comment by seanf** [comment]
@bang88 I've added another commit to upgrade TypeScript and remove byots. Feel free to use it or omit it.

**Comment by seanf** [comment]
@bang88 I think I have a workaround using ts.forEachChild.

**Comment by BANG88** [comment]
@seanf LGTM. and yes at this moment can not find a well documented Typescript compiler api. so your PR are very welcome. Thanks

**Comment by BANG88** [comment]
Are we good to go with this change ?

**Comment by seanf** [comment]
@bang88 Yep, I think so.

**Comment by BANG88** [comment]
@seanf Thanks for this PR . please check the latest version `0.2.0`

**Comment by seanf** [comment]
Great, thanks @bang88

**Pull request merged**
